name: osum_serializable
description: Serialize almost everything you every need!
version: 0.0.1
homepage: https://github.com/aswinmurali-io/osum_serializable

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  intl: ^0.17.0
  json_serializable: ^6.3.2

flutter:
