# Check code formatting + run tests

name: osum_serializable

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Get packages
      - run: flutter pub get
      
      - name: Check for code formatting
      - run: flutter format . --dry-run --set-exit-if-changed
      
      - name: Run tests
      - run: flutter test
