# Check code formatting + run tests

name: osum_serializable

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  code:
    name: Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "master"

      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .

      # - name: Analyze project source
      #   run: flutter analyze

      - name: Build code
        run: flutter pub run build_runner build

      - name: Run tests
        run: flutter test
